name: Docker Build and Push votantes-ui

on:
  push:
    branches:
      - main
    paths:
      - 'votantes-ui/**'  # Solo se activará si hay cambios en votantes-ui

jobs:
  build-and-push:
    runs-on: self-hosted  # Utilizamos el runner local

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Iniciar sesión en Docker Registry privado
      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: 10.51.15.42:5000

      # 3. Construir la imagen Docker optimizada para votantes-ui
      - name: Build Docker image for votantes-ui
        run: |
          cd votantes-ui
          docker build -t 10.51.15.42:5000/votantes-ui:latest -f Dockerfile .

      # 4. Subir la imagen Docker al Registry privado
      - name: Push Docker image to Registry
        run: |
          docker push 10.51.15.42:5000/votantes-ui:latest